mock = true   # If true, program generate fake serial data
station = "dev-station"

[daq]
watch_dir = ".daq_watch"
measurement = "flow_test_rig"
metadata_measurement = "flow_test_rig_meta"
base_tags = { rig = "mock_dev" }          # optional static tags
buffer_max_size = 30           # lines
buffer_max_age_seconds = 30.0  # force flush

[mass]
units = "g"

[mass.serial]
port = "/dev/ttyACM0"            # Scale serial port (e.g., COM10)
baudrate = 2400
bytesize = 7
parity = 'E'

[alicat_shared.serial]           # one port for all Alicats
port = "/dev/ttyUSB0"
baudrate = 19200
timeout = 0.5

[flow]
full_scale_min = 0.0
full_scale_max = 20.0
unit_id = "A"
flow_unit = "SLPM"
# no serial uses alicat-shared

[high-dp]
full_scale_min = 0.0
full_scale_max = 5.0
unit_id = "C"
pressure_unit = "PSI"
# no serial shared

[low-dp]
full_scale_min = 0.0
full_scale_max = 2.0
unit_id = "B"
pressure_unit = "INH2O"
# no serial shared
